export enum CallbackName {
    drawAreasDragMove = 'drawAreasDragMove',
    onclickMapPlaceId = 'onclickMapPlaceId',
    onclickMapGetAddress = 'onclickMapGetAddress',
    onclickMapCoordinates = 'onclickMapCoordinates',
    detailsAddressResultPoint = 'detailsAddressResultPoint',
    geocoderAddressResult = 'geocoderAddressResult',
    searchResult = 'searchResult',
    searchDetailsResult = 'searchDetailsResult',
    changedBoundsMap = 'changedBoundsMap',
    initMap = 'initMap',
    responseMapError = 'responseMapError',
    createRadius = 'createRadius',
    radiusChanged = 'radiusChanged',
    radiusDragEnd = 'radiusDragEnd',
    drawAreaStart = 'drawAreaStart',
    drawAreaDragEnd = 'drawAreaDragEnd',
    countLoadMarkers = 'countLoadMarkers', 
    markerClick ='markerClick', 
    markerDraggableEnd = 'markerDraggableEnd',
    markerDraggable = 'markerDraggable',
    infoRoute = 'infoRoute',
}
